### PR TITLE
Add metadata extension doc

### PR DESCRIPTION
**Pull request by tfili**
We need to wait for https://github.com/AnalyticalGraphicsInc/cesium/pull/7196 to be merged so we make sure the format is locked in.

### CODE REVIEW

**Comment by tfili** [comment]
@Shezan10

**Comment by mramato** [comment]
CC @shehzan10

**Comment by shehzan10** [comment]
LGTM. 👍

**Comment by pjcozzi** [comment]
👍

**Comment by tfili** [comment]
@abwood Are you good with this?

**Pull request merged**
